language: node_js

sudo: required

node_js:
  - "8"

branches:
  only:
    - master

install:
  - npm install
  - npm install -C ./context-provider


before_script:
  - npm run lint:md
  - npm run lint:text


script:
  - npm test -C ./context-provider


notifications:
  on_success: change
  on_failure: always
