branches:
  only:
    - master

services:
  - docker

jobs:
  include:
    - stage: test
      name: "Context Provider"
      language: node_js
      node_js:
        - "10"
      install:
        - npm install -C ./context-provider
      script:
        - npm test -C ./context-provider
     
    - stage: test
      name: "Documentation Tests"
      language: node_js
      node_js:
        - "10"
      install:
        - npm install
      script:
        - npm run lint:md
        - npm run lint:text

    - stage: test
      name: "Dockerfile Tests"
      language: bash
      before_script:
        - docker pull hadolint/hadolint
      script:
        - docker run --rm -i hadolint/hadolint < ./docker/Dockerfile


notifications:
  on_success: change
  on_failure: always
